blog_site/accounts/urls.py
from django.urls import path
from . import views

app_name  = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view,name='signup'),
    path('login/', views.login_view,name='login'),
    path('logout/', views.logout_view,name='logout'),
]

blog_site/blog/urls.py
from django.urls import path
from . import views

app_name  = 'blog'


urlpatterns = [
    path('',views.index,name='index'),
    path('create/',views.create_post,name='create'),
    path('<str:slug>/',views.article_detail,name='detail'),
]

blog_site/blog_site/urls.py
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',include('blog.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog_site/accounts/models.py
from django.db import models

# Create your models here.

blog_site/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=1000)
    typo = models.CharField(max_length=30)
    slug = models.SlugField(blank=True,null=True)
    body = models.TextField(max_length=50000)
    thumnail = models.ImageField(default='',blank=True)
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE,)

    def save(self,*args,**kwargs):
        if not self.slug and self.title:
            self.slug = slugify(self.title[0:50]+'-'+ (self.typo))
        super(Article,self).save(*args,**kwargs)


    def __str__(self):
        return self.title

    def info(self):
        return self.body[0:100]

    def time(self):
        if (len(self.body) >100):
            return '4 Mins'
        else:
            return '2 Mins'

blog_site/blog/forms.py
from django import forms
from .models import Article

class CreateArticle(forms.ModelForm):
	class Meta:
		model = Article
		fields = ['title','typo','body','thumnail']

blog_site/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
# login import
from django.contrib.auth import login,logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:index')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # login in to user
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
                return redirect('blog:create')
            return redirect('blog:index')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form })

def logout_view(request):
    logout(request)
    return redirect('blog:index')

blog_site/blog/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def index(request):
    articles = Article.objects.all()
    return render(request,'blog/index.html',{'articles':articles})

def article_detail(request,slug):
    articles = Article.objects.get(slug=slug)
    # return HttpResponse(slug)
    return render(request,'blog/detail.html',{'article':articles})

@login_required(login_url ='/accounts/login/')
def create_post(request):
    if request.method == 'POST':
        form= forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            print(instance.author)
            form.save()
            instance.save()
            return redirect('blog:index')
    else:
        form = forms.CreateArticle()
    return render(request,'blog/create_post.html',{'form':form})
    # return HttpResponse("hello")

blog_site/templates/accounts/login.html
{% extends 'base.html' %}

 {% block heading %}
        <h1 class="hello">Login</h1>
        <hr class="small">

    
{% endblock %}

{% block content %}
    <!-- <p class="login">Thisi login</p> -->

    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
            <p>You must be login to Create Blog post</p>
        {% endif %}
        {% csrf_token %}
        {{form}}
        
        <input type="submit" value="Login">
    </form>
{% endblock %}

blog_site/templates/accounts/signup.html
{% extends 'base.html' %}

 {% block heading %}
        <h1>SIgn Up</h1>
        <hr class="small">
    

{% endblock %}
        
{% block content %}
        <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Sign Up">
    </form>
{% endblock %}

blog_site/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <meta name="description" content=""> -->
    <!-- <meta name="author" content=""> -->

    <title>Blog</title>
    <style type="text/css">
        
    </style>
    <!-- <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" /> -->
    <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.ico">
    <!-- <link rel="icon" href="{{ STATIC_URL }}images/favicon.ico" />  -->
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'custom_css/style.css' %}" rel="stylesheet">

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'blog:index' %}"">Blog990.com</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'blog:index' %}"">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:create' %}">Create Post</a>
                    </li>
                     {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'accounts:logout' %}">Logout</a>

                          <!-- <form class="logout-link" method="post" action="{% url 'accounts:logout' %}">
                            {% csrf_token %}
                              <button type="submit" >Logout</button>
                          </form> -->
                        </li>
                      {% else %}
                      <li>
                        <a href="{% url 'accounts:signup' %}">Sign Up</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:login' %}">Login</a>
                    </li>

              {% endif %}

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('{% static 'img/home-bg.jpg' %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                    {% block heading %}
                    {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </header>
<div class="container">
{% block content %}

 
{% endblock %}
</div>
    <!-- <hr> -->
    <!-- Footer -->
    <hr>
    <footer class="bg-success">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <!-- <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul> -->
                    <p class="copyright text-muted p-5" style="font-size: 20px;">Copyright &copy; Blog990.heroku.com {% now 'Y' %}</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/slugify.js' %}"></script>
    
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

blog_site/templates/blog/create_post.html
{% extends 'base.html' %}

{% block heading %}
        <!-- <h2 class="text-capitalize">Create the new post</h2>     -->
        <h2 class="h2-title">Create the new post</h2>
        
{% endblock %}


{% block content %}
        <div class="create-post">
        <form class="site-form" method="post"action="" enctype="multipart/form-data">
                 {% csrf_token %} 
                 {{ form }}
                <input type="submit" value="Create Blog"> 
        </form>
    </div> 

{% endblock %}

blog_site/templates/blog/detail.html
{% extends 'base.html' %}

{% block heading %}
        <h2 class="h2-title">{{ article.title }}</h2>
         <p>Posted By : <span class="text-white">{{ article.author }} </span>on {{ article.date }} </p>
        <hr class="small">
{% endblock %}


{% block content %}

<article class="">
    <div class="containerr">
      <div class="row">
        <div class="col-lg-10 col-md-8 mx-auto text-center">
        <img src="{{ article.thumnail.url }}" class="img-responsive"  style="height: 400px;width: 700px; padding-left: 30%;" />

        <p>{{ article.body }} </p>
                
        </div>
      </div>
    </div>
  </article><hr>
{% endblock %}

blog_site/templates/blog/index.html
{% extends 'base.html' %}

 {% block heading %}
        <h1>Blog</h1>
        <hr class="small">
        <span class="subheading">“If you want to be a writer, you must do two things above all: Read a lot and write a lot”</span>
{% endblock %}


  <!-- Main Content -->
  <!-- <div class="container"> -->
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
              {% block content %}
              {% for article in articles %}

              <div class="post-preview">
                 <a href="{% url 'blog:detail' slug=article.slug %}">
                   <h2 class="post-title ">
                     {{ article.title }}
                   </h2>
                   <h3 class="post-subtitle text-capitalize" style="word-spacing: 10px;  letter-spacing: 1px;">
                     {{ article.info }}
                   </h3>
                 </a>
                 <p class="post-meta">Posted by
                          <a href="#">{{ article.author }}</a>
                                 {{ article.date }} - {{ article.time }}</p>
              </div>
        <hr> 
        {% endfor %}
              {% endblock %}
        }
      </div>
    </div>
  <!-- </div> -->